# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "post-purchase"
client_id = "2b05c2c0be5a7df132412f6ebaf5955d"
application_url = "https://mistake-defeat-consistency-area.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://mistake-defeat-consistency-area.trycloudflare.com/auth/callback",
  "https://mistake-defeat-consistency-area.trycloudflare.com/auth/shopify/callback",
  "https://mistake-defeat-consistency-area.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pluspostpurchase.myshopify.com"
