type = "checkout_post_purchase"
name = "my-post-purchase-ui-extension"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
